### PR TITLE
Some people are still having troubles with image loading. It's like that one OkHttp bug all over again.

### PR DESCRIPTION
**Pull request by K1rakishou**
Add one important log to see what the fuck is going on for people who can't load images whatsoever.
The cause is IOException but I wonder what's the explanation to it (if there is any at all) so I want to log it.

### CODE REVIEW

**Comment by K1rakishou** [comment]
Maybe it's something OkHttp related again.

**Comment by K1rakishou** [comment]
We might even have to disable HTTP/2 again. Because I have a hunch it's because of it. The previous bug was related to HTTP/2 too.

Maybe we could add a setting to disable everything other than HTTP 1.0/1.1 so people who have trouble with image loading could check it out whether it helps or not?

**Comment by Pentaphon** [comment]
I would disable HTTP/2 by default and make it opt-in until HTTP/2 support matures. I'm sure bug reports would stop once you do that.

**Comment by Adamantcheese** [comment]
HTTP/2 is generally well supported enough for it to be used, and I won't disable it until I have good confirmation that it is because of HTTP/2. If it is, then it is a result of OkHttp, and those issues should be forwarded to them to improve that library.

**Comment by Pentaphon** [comment]
> If it is, then it is a result of OkHttp, and those issues should be forwarded to them to improve that library.

It's almost certain at this point it is because of OkHttp's HTTP/2, so while they get those issues fixed, I think it makes sense to disable it by default but allow users to enable it so they can help OkHttp fix their issues. All we are doing is ensuring that people keep sending you duplicates of the same bug. Is there a pressing need for HTTP/2 right now? I doubt it.

**Comment by K1rakishou** [comment]
>and I won't disable it until I have good confirmation that it is because of HTTP/2.

Well we just had a similar bug with their HTTP/2 implementation. And this one is really similar to that one. I bet it's yet another OkHttp bug.

Yesterday an anon recorded a video where the app just refuses to start loading images. Then he sent a link to it to dashchan and dashchan started loading it right away. IIRC dashchan uses HttpURLConnection (god forbid) and only supports HTTP/1.1. Then he sent me the logs where I could clearly see that he was using Wi-Fi connection, there were just a couple of requests in the queue and that he was getting IOExceptions with huge timeouts. 

That's why I'm thinking it's another HTTP/2 issue.

**Comment by Pentaphon** [comment]
> That's why I'm thinking it's another HTTP/2 issue.

I honestly don't see what's the harm in disabling HTTP/2 by default, even just temporarily, to see if any new bug reports show up.

**Pull request merged**
