### PR TITLE
Video stream fixes

### LINKED ISSUE #62: [BUG] WebM's with sound start playing in the background even when they're supposed to be muted, only way to stop it is FC'ing app
Steps to reproduce:
1. Find a thread that has WebM's with sound (in /wsg/ for example)
2. Open a WebM and start swiping through them quickly (don't wait for them to load)
3. Audio for the WebM's you have swiped past will start to play in the background (even when WebM's are set to be muted by default)
4. Only way to stop the background audio from playing is to force close the app from settings

### PR DESCRIPTION
**Pull request by ekisu**
Fixes #62.

Sorry for the commit spam, just squash this if it's alright.

### CODE REVIEW

**Comment by Adamantcheese** [comment]
That threadpool thing MUST be in the application when built with the release configuration. Otherwise it'll crash with "Http on main thread". Test it out first and make sure that you don't need that, otherwise change it real quick before I merge it.

**Comment by Adamantcheese** [comment]
Also squashing means I don't get the insane graphs when looking at the tree view, which is just fun really, so every commit goes in.

**Comment by Adamantcheese** [comment]
I stand corrected I didn't see your one commit where you mentioned removing the threadpool. I'll double check it doesn't crash though and immediately merge it if so.

**Comment by ekisu** [comment]
It's okay, I didn't know it crashed the app on Release builds. I'm trying to test it right now (~~if android studio manages to actually fucking work~~).

edit: works for me (tm).

**Pull request merged**
