### PR TITLE
(#252) Captcha queueing

### LINKED ISSUE #252: [IMPROVEMENT] Add ability to enter multiple captchas before posting, use entered captchas until they expire
UPD: For some reason one captcha cannot be used to make multiple posts right now. 4chanx just removes a captcha after the reply. I dunno whether it depends on the board or 4chan does not support it anymore (I tested it on /g/ and /qa/). So, for now, one captcha will be used to make one post. But you still will be able to enqueue multiple captchas. Once I figure out why it does not work (and if it is still possible) I will make captchas to be used until expired rather than one per a post.

### PR DESCRIPTION
**Pull request by K1rakishou**
Closes #252

### CODE REVIEW

**Comment by K1rakishou** [comment]
Ready to be merged.

**Comment by Adamantcheese** [comment]
Alright, will do today or tomorrow.

**Comment by Adamantcheese** [comment]
Is there any particular reason why you've messed with ReplyLayout more than just adding in your authenticate button? Left is what it was originally, right is what it is now.
wut

**Comment by K1rakishou** [comment]
What the hell. I only remember setting "tools:visibility="visible"" for every hidden view so it's more obvious what the layout looks like in the preview mode and adding my button. Looking at the layout now it's like completely different from what it was before. Maybe Ctrl+Alt+L somehow sorted the layout instead of just formatting it? In any case, this isn't intentional. Thanks for double-checking before merging.

**Comment by K1rakishou** [comment]
Huh, for some reason when I press Ctrl+Alt+L to reformat the xml it fucking changes it's ordering completely. I usually press Ctrl+Alt+L all the time unconsciously so I didn't even notice that it has reordered the xml. Gotta be careful with this shit from now on.

**Comment by K1rakishou** [comment]
Alright, the bug is fixed, layout reverted back so it can be merged.

**Comment by Adamantcheese** [comment]
Weird that reformat code messes up your formatting that much. I've got Ctrl + S mapped to a macro that reformats the current file and saves all open files, and I've never had it do that to me. Maybe you have a different code style set up that formats differently than default.

**Comment by K1rakishou** [comment]
Well, I don't remember touching it at all. That's really strange.

**Comment by Adamantcheese** [comment]
Android Studio doing whatever it wants. Eh, whatever. Minor issue. Thanks for the quick fix.

**Pull request merged**
