### PR TITLE
(#304) Pass WatchManager to ChanLoader via constructor instead of cre…

### LINKED ISSUE #304: [BUG] Cyclic instantiation of WatchManager class
This was causing the slow app load time.

unknown

### PR DESCRIPTION
**Pull request by K1rakishou**
…ating it inside of the ChanLoader to avoid cyclic dependency instantiation

Fixes slow app load time.

Closes #304

### CODE REVIEW

**Comment by Adamantcheese** [comment]
By the way, it's not that this was CYCLIC, because that would cause it to never actually load the application at startup; it's that if you had saved threads then it would start trying to load up all of those when the watch manager instance was still being created, causing the injector to believe that the watch manager instance hadn't been made yet, because it doesn't block on singleton instance creation. So every time one of those instance calls was called, it's not that Feather was at fault, just that instantiating the watch manager took longer than the initialization of the rest of the application. This does go around that problem, but I still think Feather shouldn't really let that happen.

**Comment by K1rakishou** [comment]
Huh, I didn't even notice that the instantiation in feather wasn't blocking. That's strange. Why would they do it like this I wonder.

**Comment by Adamantcheese** [comment]
I don't think Feather is meant to be used for multithreaded contexts is all. It's lightweight, but that also means that it's missing a lot of more complicated features and protections. Not really a big deal to work around it for this case.

**Comment by K1rakishou** [comment]
Ohhh, so the problem was that the instantiate() method was called from multiple threads. I though that the implementation of instantiate() is asynchronous. Now I see.

**Pull request merged**
