### PR TITLE
Bunch of fixes and improvements related to SAF/FSAF, image loading etc

### LINKED ISSUE #694: Crash report "kotlin.NotImplementedError: Not implemented for com.github.k1rakishou.fsaf.file.ExternalFile, fileManagerId = com.github.k1rakishou.fsaf.file.FileManagerId@c9ebc8b"
UUID: 27d374cf73e2d2d015cc99cd56e97f9c
Build flavor: stable
Version name: v4.11.1
OS info: Android 8.0.0, sdk version: 26
Report description: No title
Logs:
```
=== LOGS ===
E/Kuroba | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-0]: Error while trying to download, class = FileNotFoundOnTheServerException, message = FileNotFoundOnTheServerException
E/Kuroba | FileCacheV2: [NormalFileCacheV2Thread-0]: Exception for request [FileDownloadRequest: url = https://media.8kun.top/file_store/e48944a49ab95c83e731419fed6386602904c0cb7af1e9cd625b85563b2f8XXX.jpg, outputFileName = baee1026751fe9e4b04e7d1f68b786fd.cache], network class = WIFI, downloads = 1
E/Kuroba | FileCacheV2: com.github.adamantcheese.chan.core.cache.downloader.FileCacheException$FileNotFoundOnTheServerException: FileNotFoundOnTheServerException
E/Kuroba | FileCacheV2: 	at com.github.adamantcheese.chan.core.cache.downloader.ChunkPersister$storeChunkInFile$1.subscribe(ChunkPersister.kt:53)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
E/Kuroba | FileCacheV2: 	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
E/Kuroba | FileCacheV2: 	at io.reactivex.Flowable.subscribe(Flowable.java:14882)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:68)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
E/Kuroba | FileCacheV2: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/Kuroba | FileCacheV2: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/Kuroba | FileCacheV2: 	at java.lang.Thread.run(Thread.java:764)
E/Kuroba | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-2]: Error while trying to download, class = FileNotFoundOnTheServerException, message = FileNotFoundOnTheServerException
E/Kuroba | FileCacheV2: [NormalFileCacheV2Thread-2]: Exception for request [FileDownloadRequest: url = https://media.8kun.top/file_store/e48944a49ab95c83e731419fed6386602904c0cb7af1e9cd625b85563b2f8XXX.jpg, outputFileName = baee1026751fe9e4b04e7d1f68b786fd.cache], network class = WIFI, downloads = 2
E/Kuroba | FileCacheV2: com.github.adamantcheese.chan.core.cache.downloader.FileCacheException$FileNotFoundOnTheServerException: FileNotFoundOnTheServerException
E/Kuroba | FileCacheV2: 	at com.github.adamantcheese.chan.core.cache.downloader.ChunkPersister$storeChunkInFile$1.subscribe(ChunkPersister.kt:53)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
E/Kuroba | FileCacheV2: 	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
E/Kuroba | FileCacheV2: 	at io.reactivex.Flowable.subscribe(Flowable.java:14882)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:68)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
E/Kuroba | FileCacheV2: 	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
E/Kuroba | FileCacheV2: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/Kuroba | FileCacheV2: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/Kuroba | FileCacheV2: 	at java.lang.Thread.run(Thread.java:764)
E/Kuroba | ConcurrentChunkedFileDownloader: [NormalFileCacheV2Thread-3]: Error while trying to download, class = CancellationException, message = CancellationException for request with url = https://media.8kun.top/file_store/6e57bf512c5c5d91bf98171b0c995d311ad672fb7d7b321b059c266d71e4dXXX.jpg, state = Canceled
E/FileManager: Base directory class com.github.adamantcheese.chan.ui.settings.base_directory.LocalThreadsBaseDirectory with path /storage/emulated/0/Kuroba/saved_threads does not exist!
E/Kuroba | ViewThreadController: saveClickedInternal() fileManager.newLocalThreadFile() returned null
E/FileManager: Base directory class com.github.adamantcheese.chan.ui.settings.base_directory.LocalThreadsBaseDirectory with path /storage/emulated/0/Kuroba/saved_threads does not exist!
E/Kuroba | ViewThreadController: saveClickedInternal() fileManager.newLocalThreadFile() returned null
E/Kuroba | UNCAUGHT: Called from unhandled exception handler.
E/Kuroba | UNCAUGHT: kotlin.NotImplementedError: Not implemented for com.github.k1rakishou.fsaf.file.ExternalFile, fileManagerId = com.github.k1rakishou.fsaf.file.FileManagerId@c9ebc8b
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.FileManager.getName(FileManager.kt:656)
E/Kuroba | UNCAUGHT: 	at com.github.k1rakishou.fsaf.FileManager.areTheSame(FileManager.kt:844)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.ui.controller.settings.base_directory.SharedLocationSetupDelegate.askUserIfTheyWantToMoveOldSavedFilesToTheNewDirectory(SharedLocationSetupDelegate.kt:102)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$onSaveLocationUseSAFClicked$1$onResult$2.invoke(MediaSettingsControllerPresenter.kt:147)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$onSaveLocationUseSAFClicked$1$onResult$2.invoke(MediaSettingsControllerPresenter.kt:120)
E/Kuroba | UNCAUGHT: 	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$withCallbacks$$inlined$let$lambda$1.run(MediaSettingsControllerPresenter.kt:263)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.handleCallback(Handler.java:789)
E/Kuroba | UNCAUGHT: 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/Kuroba | UNCAUGHT: 	at android.os.Looper.loop(Looper.java:164)
E/Kuroba | UNCAUGHT: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
E/Kuroba | UNCAUGHT: 	at java.lang.reflect.Method.invoke(Native Method)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/Kuroba | UNCAUGHT: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: END OF CURRENT RUNTIME MESSAGES
E/Kuroba | UNCAUGHT: ------------------------------
E/Kuroba | UNCAUGHT: Android API Level: 26
E/Kuroba | UNCAUGHT: App Version: v4.11.1
E/Kuroba | UNCAUGHT: Development Build: No
E/Kuroba | UNCAUGHT: Phone Model: samsung SM-G930P


=== STACKTRACE ===
Called from unhandled exception handler.
kotlin.NotImplementedError: Not implemented for com.github.k1rakishou.fsaf.file.ExternalFile, fileManagerId = com.github.k1rakishou.fsaf.file.FileManagerId@c9ebc8b
	at com.github.k1rakishou.fsaf.FileManager.getName(FileManager.kt:656)
	at com.github.k1rakishou.fsaf.FileManager.areTheSame(FileManager.kt:844)
	at com.github.adamantcheese.chan.ui.controller.settings.base_directory.SharedLocationSetupDelegate.askUserIfTheyWantToMoveOldSavedFilesToTheNewDirectory(SharedLocationSetupDelegate.kt:102)
	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$onSaveLocationUseSAFClicked$1$onResult$2.invoke(MediaSettingsControllerPresenter.kt:147)
	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$onSaveLocationUseSAFClicked$1$onResult$2.invoke(MediaSettingsControllerPresenter.kt:120)
	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$withCallbacks$$inlined$let$lambda$1.run(MediaSettingsControllerPresenter.kt:263)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)


=== SETTINGS ===
Prefetching enabled: false
Thread downloading enabled: true, active downloads = 0
Hi-res thumbnails enabled: false
Youtube titles parsing enabled: true
Youtube durations parsing enabled: false
Concurrent file loading chunks count: 2
WEBM streaming enabled: false
Saved files base dir info: Java API location: /storage/emulated/0/Kuroba/files, SAF location: content://com.android.providers.downloads.documents/tree/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2F4chan, active: SAF
Local threads base dir info: Java API location: /storage/emulated/0/Kuroba/saved_threads, SAF location: , active: Java API
Phone layout mode: AUTO
```

### LINKED ISSUE #696: Crash report "java.lang.SecurityException: Document 2562 is not a descendant of downloads"
UUID: 47d1fb120a93a58a6114472823481032
Build flavor: stable
Version name: v4.11.1
OS info: Android 10, sdk version: 29
Report description: No title
Logs:
```
java.lang.SecurityException: Document 2562 is not a descendant of downloads
	at android.os.Parcel.createException(Parcel.java:2071)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:719)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1705)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1521)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:1205)
	at com.github.k1rakishou.fsaf.manager.ExternalFileManager.getInputStream(ExternalFileManager.kt:287)
	at com.github.k1rakishou.fsaf.FileManager.getInputStream(FileManager.kt:642)
	at com.github.k1rakishou.fsaf.FileManager.copyFileContents(FileManager.kt:356)
	at com.github.k1rakishou.fsaf.FileManager.copyDirectoryWithContent(FileManager.kt:490)
	at com.github.adamantcheese.chan.core.presenter.MediaSettingsControllerPresenter$moveFilesInternal$1.run(MediaSettingsControllerPresenter.kt:221)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

### PR DESCRIPTION
**Pull request by K1rakishou**
Closes #694, #687, #638, #579, #703 
Maybe closes #696, #690, #560

- Update FSAF to v1.0-alpha36. (Snapshots have been reworked, a bug related to snapshots has been fixed (now we shouldn't see bugs where files or directories cannot be created for some unknown reason),
some changes to clone() methods, flattenSegments() implementation, get rid of cloneUnsafe() in Kuroba and some other changes).
- Move handleLocalThreadFile() method call to a background thread to avoid micro freezes when swiping images in a local thread.
- Do not download inlined files for local threads (inlined files now have isInlined flag set to true, it's false by default and only being set in one place - where we parse them).
- Use new Snapshots in ThreadSaveManager.
- Try to create default base directories, if they weren't set by the user and do not exist, when trying to download an image or an album.
- A little bit of optimization for getSaveLocation(). First of all, it won't be called twice now. Second, it will return a flattened AbstractFile (no intermediate segments).
- Fix MissingBackpressureException when downloading thread albums.
- Fix app freezing (and depending on how many images in a thread even ANRing) when downloading thread albums. Because we need to check a lot of stuff before downloading an album (like create all the necessary directories, deduplicate the file name, etc).
- Relax directory and file name filtering rules. Previous regex was really strict, so if an image contained any non-english letters, they would all be replaced with _ which is a big problem for
non-english image boards (almost every image name would contain lots of _ symbols and it could even cause collisions). Now it only filters out special symbols and periods (only in directory names). Everything else is allowed.
- Do not download inlined files when downloading thread albums. Some of the hosts are bad and cause SSL exceptions and other stuff. Also, inlined files may be really big and we can't check how big they are unless we download them first.
- Fix bugs related to not being able to move files from an old base directory to a new one when both of them are using the same file provider (update FSAF to v1.0-alpha38)

### CODE REVIEW

**Comment by Adamantcheese** [comment]
This looks good and all, but what issues does this close? There's quite a few of them and it would be good to close them out when this gets merged.

**Comment by K1rakishou** [comment]
Oh yeah, I forgot to link them.

**Comment by K1rakishou** [comment]
Alright, I linked some issues that are related to this PR.

**Comment by K1rakishou** [comment]
Wait, do not merge this one yet. I'm gonna change how we copy the apk that we download in UpdateManager to use SAF so we don't have those strange errors anymore.

**Comment by K1rakishou** [comment]
Alright, it's ready.

**Comment by Adamantcheese** [comment]
Yeah I dunno about that last commit. Seems like it's gonna get super annoying for people on dev.

**Comment by K1rakishou** [comment]
Well, probably. But at least it shouldn't crash anymore with this #703 message

**Comment by K1rakishou** [comment]
It seems like this (https://stackoverflow.com/questions/42516126/fileprovider-illegalargumentexception-failed-to-find-configured-root) is the solution but since I can't reproduce it and I have no idea what's going on there I can't use it

**Comment by K1rakishou** [comment]
And it seems like we are already doing the same thing. We have both cache-path and external-cache-path so I have no idea what it doesn't like.

**Comment by K1rakishou** [comment]
I can revert the last commit if you have a better solution that does not involve SAF.

**Comment by Adamantcheese** [comment]
I think I'd be fine with a setting in Behvaiour -> Other that disabled the check, with the setting being "show the dialog" by default.

**Comment by K1rakishou** [comment]
Alright.

**Pull request merged**
