### PR TITLE
Post Storage Access Framework integration fixes and improvements

### LINKED ISSUE #409: [IMPROVEMENT] Stop (not cancel) all threads downloadings (in the settings file) when exporting settings with local dirs base directory using SAF directory
Right now it starts downloading them in the default directory (so you if you don't change the base directory quickly enough you will have your threads located in two directories) and you can't change it right away after importing settings because there are active downloads. This should only be applied to the settings file not the real downloading threads! 
In other words, currently downloading threads should be exported as stopped. If a thread is already fully downloaded the do not change anything for ir.

### PR DESCRIPTION
**Pull request by K1rakishou**
~~So that people are warned to NOT move files or delete files when old base directory == new base directory.~~
~~Also fix a bug when importing settings right after app reinstall which would fail the importing process because of absence of the shared_prefs file.~~

What's new:
- Removed warnings when moving files from one base directory to another or deleting files in an old base directory after moving them to a new one.
- You now cannot select the same directory via the Java FIle api and via SAF.
- You now cannot use one directory for both saved file storage and local threads storage. This limitation comes from SAF and FSAF. Otherwise there is just no way for me to compare two AbstractFiles and figure out whether they point to the same file/directory or not.
- Request WRITE_EXTERNAL_STORAGE permissions when attempting to change a base directory in the media settings.

Things that should be tested:
- Moving saved files / local threads from a java file backed base directory to a SAF backed base directory with and without old files deletion.
- Attempt to select the same directory twice (first you select any directory in the external storage via java file api then you select the same directory via SAF)
- Attempt the move files between directories that have similar hierarchy but belong to different file implementations (like Kuroba/files in the external storage and Kuroba/dev somewhere on an sd-card).
- Settings exporting with actively downloading threads when local threads base directory is on as sd-card and when it's not (when local threads base dir is located on an sd-card it should be reset to default in the settings file). The same for saved files. When exporting settings the warning should change depending on whether you have local threads / saved files base dir located on an sd-card or not somewhere in the external storage, and whether you have actively downloading threads. If local threads base dir is located on an sd-card and you have threads being downloaded they should be marked as stopped in the settings file. Also the pins associated with those threads shouldn't have the "download thread" flag.
- When importing settings the base directories should be reset to default paths if they were pointing to the SAF backed directories before being exported. If they were not then they should remain the same.

I hope I didn't forget anything.

Also closes #409, #415 and #423

### CODE REVIEW

**Comment by Adamantcheese** [comment]
Wouldn't it be better to just not present the move/delete operation if the base and new directories are the same? Some of your comments seem to say that with the SAF stuff it's not exactly guaranteed that two same type files (Raw or External) will be equivalent with the `equals` function, so I'm not sure if what I would code would be correct.

Also in `FileManager.kt` your `copyDirectoryWithContent` function doesn't check if the source and destination are equivalent to prevent extra work being done, not sure if that was an oversight or not.

**Comment by K1rakishou** [comment]
Yeah it would be better but the function to compare paths for different AbstractFiles is not implemented yet. That's why I've decided to add warnings for now.
https://github.com/K1rakishou/Fuck-Storage-Access-Framework/issues/4

**Comment by Adamantcheese** [comment]
Your `equals` function in AbstractFile checks the classes of the inputs, so shouldn't that be enough to say that a RawFile and and ExternalFile aren't equivalent, even if they point to the same location pathwise? So if you move from a base Raw directory to an External directory, even though you've moved nothing, they're technically different so the delete dialog can be ignored based on that? Or am I being dumb and missing something obvious.

**Comment by K1rakishou** [comment]
Well, when using SAF you can selected any kind of directory or file be it on an SD-card or in the internal/external memory while when using regular java files you can't access SD-card at all. So in theory when switching from a SD-card base directory to a regular java file base directory you technically can choose the same directory twice and for now it's impossible figure out whether they are the same or not (because SAF directories contain lot's of bullshit in the Uri). You can't just assume that they are different because they are backed by different file API implementations.

**Comment by K1rakishou** [comment]
So detecting whether two AbstractFiles are pointing to the same file turned out to be harder than I had excepted. The `areTheSame()` function is done but there were problems in how I'm detecting what directory to use (regular or SAF) in Kuroba. So I had to rewrite lots of code and it's almost done. I think I will complete this shit tomorrow so I guess don't merge until then. I will remove the warnings as well since we won't need them anymore.

**Comment by Adamantcheese** [comment]
I can delay for a week, take your time, there's no rush.

**Comment by K1rakishou** [comment]
So this has turned out to be even more harder than I previously expected. The amount of corner-cases I have to take care of is just ridiculous. So yeah, I will probably have to delay this PR until the next weekends. I'm going to think about how to do it in a more simple way for now.

**Comment by K1rakishou** [comment]
Ready to be merged.

**Pull request merged**
