### PR TITLE
(#480) Change the archives link to a new working one

### LINKED ISSUE #480: [BUG] Archives json file was moved to another repository
We should update the link
```
2019-12-30 14:33:46.908 E/Volley: [8640] BasicNetwork.performRequest: Unexpected response code 404 for https://mayhemydg.github.io/archives.json/archives.json
```

To this one:
https://nstepien.github.io/archives.json/archives.json

https://github.com/ccd0/4chan-x/issues/2520

### PR DESCRIPTION
**Pull request by K1rakishou**
Closes #480

### CODE REVIEW

**Comment by Adamantcheese** [comment]
I'm closing this because https://github.com/Adamantcheese/Kuroba/commit/653aa1e1ded4b642e62714eaf55b0b9d9803e863 solves it in a better fashion.

**Comment by K1rakishou** [comment]
Will this result in a build error if the url ends up dead again?

**Comment by Adamantcheese** [comment]
Shouldn't anymore; will skip downloading if it fails, so no internal file will be available. See https://github.com/Adamantcheese/Kuroba/commit/84a5fd1b1a3181585ae257d183f18aa9c90a25af

**Comment by K1rakishou** [comment]
Maybe it would be better to fail the build?

**Comment by Adamantcheese** [comment]
Nah, if it fails to download then it'll fail to get them from the URL in the app itself. Better to not hold up a build on something that isn't strictly necessary for it to function, as this is really to make sure that there's some sort of archive list to provide some amount of functionality (even if it might be slightly wrong at some point).

**Comment by K1rakishou** [comment]
Well, probably you are right, it's not like this happens every day.

**Pull request closed without merging**
