### PR TITLE
Even more updates and cleanup

### PR DESCRIPTION
**Pull request by TacoTheDank**
Hello again. It's the usual.

### 1st commit
- Update `de.undercouch:gradle-download-task` 4.0.4 -> 4.1.1 ([changelog](https://github.com/michel-kraemer/gradle-download-task/releases))
- Update AndroidX AppCompat 1.2.0-rc01 -> 1.2.0-rc02 ([changelog](https://developer.android.com/jetpack/androidx/releases/appcompat#1.2.0-rc02))
- Replace general usage exoplayer with the modules we actually use
- Update Mockito 3.3.3 -> 3.4.6 ([changelog](https://github.com/mockito/mockito/releases))
- Update LeakCanary 2.3 -> 2.4 ([changelog](https://square.github.io/leakcanary/changelog/#version-24-2020-06-10))
- Update `com.android.tools:desugar_jdk_libs` 1.0.9 -> 1.0.10 ([changelog](https://github.com/google/desugar_jdk_libs/blob/master/CHANGELOG.md)) (1.0.11's artifact hasn't been made yet for some reason, but whatever)

### 2nd commit
- As usual, miscellaneous cleanup around the project

### 3rd commit
- Fixes a few deprecations I found (the deprecated getColor already returns theme as null, so this doesn't actually change anything as far as I'm aware)

### CODE REVIEW

**Comment by Adamantcheese** [comment]
OkHttp 4.7.2 -> 4.8.0 was done previously and reverted due to low level crypto crashes, see #1016. 
Switch is being using instead of SwitchCompat in order for the proper class to be inflated at runtime. SwitchCompat inflates a different view to what I want and will cause resource crashes otherwise.
In commit #4, you've removed the editable declaration in the XML for layout_report. This was intentional as we don't want users to edit any logs, as they seem to like to remove useful information and send reports with garbage in it.

**Comment by TacoTheDank** [comment]
First one is a strange bug indeed. I'll add a comment to the build.gradle.

If we're making an EditText non-editable, I'd say it's kinda pointless to have it. Would it be better to just change it to a MaterialTextView? In any case, I'll change it back for now. You can decide for that.

**Comment by K1rakishou** [comment]
Are you sure it's OkHttp that's causing that crash? Because I don't see anything in their repo.

**Comment by Adamantcheese** [comment]
The changelog for 4.8.0 points out some TLS changes which may be what's resulting in low-level cryptographic issues in libssl, which is what was noted in that issue's logs. https://square.github.io/okhttp/changelog/#version-480

**Pull request merged**
