### PR TITLE
(#419) Feather -> Dagger

### LINKED ISSUE #419: [IMPROVEMENT] Replace Feather with Dagger 2
Because fuck Feather for swallowing exceptions.
And dagger has lots of good checks, like, the recursive dependencies check during the project build.
Shouldn't be hard since we already use component/module schema that is similar to what dagger uses. But there will be difficulties replacing all those "Feather.instance(XXX.class)" but at least we will finally stop doing that because it's a bad practice.

### PR DESCRIPTION
**Pull request by K1rakishou**
Closes #419 
!!!NOT FOR THIS RELEASE!!!

### CODE REVIEW

**Comment by Adamantcheese** [comment]
I'm going to just close this because with all the upcoming merges, it's going to just be easier to do this from scratch, if you so choose.

**Comment by K1rakishou** [comment]
Noooo! I was waiting for all the other PRs to get merged so I can fix merge conflicts in this one!

**Comment by K1rakishou** [comment]
And it won't be easier. I spent a whole day on this PR.

**Comment by K1rakishou** [comment]
On the other hand maybe it will be easier to just do this again. We will see.

**Pull request closed without merging**
