### PR TITLE
Fix callbacks getting called on a wrong thread, reverted back thread-checks

### PR DESCRIPTION
**Pull request by K1rakishou**
Debug checks save the day once again.

### CODE REVIEW

**Comment by Adamantcheese** [comment]
And despite your debug checks, you've managed to fuck it up and put in exactly the bug I was avoiding, only worse and everywhere now.

**Comment by K1rakishou** [comment]
Well, at least we discovered it before the release. Now, if it was a synchronization issue instead, it would go straight into the release and would probably stay there for god knows how much time periodically biting us in the ass with weird crashes. Hiding and issue != fixing it.

**Comment by Adamantcheese** [comment]
Maybe I didn't explain myself well enough. I'm not merging this at all because every single onEnd call is going to throw an exception now because you're calling EVERY SINGLE ONE INSIDE A RUN ON UI METHOD. AND THEN IT IMMEDIATELY CHECKS IF IT'S THE FUCKING MAIN THREAD

**Comment by K1rakishou** [comment]
I don't get it. How is it going to throw if they are run on main thread and the check makes sure that it is run on the main thread?

**Comment by K1rakishou** [comment]
And it turns out that now we have synchronization issues which are, of course, way better than a crash.

**Comment by Adamantcheese** [comment]
```
runOnUiThread(() -> {
                    onDestination();
                    onEnd();
                });
```
```
public void onEnd() {
    BackgroundUtils.ensureMainThread();
    imageSaveTaskAsyncResult.onSuccess(success ? Success : Failure);
}
```
Look, moron, you can't even read the code you write.

**Comment by K1rakishou** [comment]
And what's the problem here? It runs the callback on the main thread and then checks whether the code is being executed on the main thread. Everything seems fine to me. Here is the function implementation:

```
    public static void ensureMainThread() {
        if (!isMainThread()) {
            if (BuildConfig.DEV_BUILD) {
                throw new IllegalStateException("Cannot be executed on a background thread!");
            } else {
                Logger.e(
                        "BackgroundUtils",
                        "ensureMainThread() expected main thread but got " + Thread.currentThread().getName()
                );
            }
        }
    }
```

**Comment by Adamantcheese** [comment]
Can you literally not read? Do you not have eyes? Run it on the fucking UI thread and then check if you're on the main thread like a complete dipshit? It's always going to fucking fail to be on the main thread with this shit you gave me.

**Comment by K1rakishou** [comment]
??? What? How is it going to fail? Main thread is UI thread. We run the code on the main (UI) thread and then check whether it's the main (UI) thread.

**Comment by Adamantcheese** [comment]
Christ al fucking mighty the fucking function names are all over the place and Android's retarded for having the UI thread and main thread be exactly the fucking same. Alright. My bad, 100%. I'm just super pissed right now because I thought that the UI and main thread were different things. I'm going to rename that stupid run on ui thread function though as soon as I merge this because holy shit am I mad.

**Comment by K1rakishou** [comment]
Wew, for a second I thoght that I'm super wrong here because of how persistant you were. But on the other hand that was impossible because I tested this code just yesterday. Well, shit happens. Glad we came to an agreement, haha.

**Comment by Adamantcheese** [comment]
What normal goddamn system uses the same thread for the UI and application logic? LITERALLY NONE. AAAAAAAAAAAAA FUCK okay I'm gonna go ahead and release this now, it's a tad late but whatever

**Comment by K1rakishou** [comment]
Yeah, it's time.

**Pull request merged**
