### PR TITLE
(#221) Local threads improvements and fixes

### LINKED ISSUE #221: [IMRPOVEMENT] Add ability to open local copies of downloading threads before they are fully downloaded
Right now you can't, you have to wait until it gets either deleted (404) or archived. And if you have no internet connection and want to read what has been already downloaded you simply can't which is bad.

### LINKED ISSUE #227: Local thread saves from an already archived thread are never "fully downloaded"
If you open up a thread from 4chan's archive via the catalog menu button, open up a thread, and try to locally download a thread, it never reaches the "finished" state. You can tell because with the most recent change for the animated vector drawable for the save icon, it never actually stops animating, and breakpoints show me that it never reaches that state.

### PR DESCRIPTION
**Pull request by K1rakishou**
Fixes #227 (you can now start downloading already archived threads), closes #221 and #265 (#291) 

~**!!!Do not merge yet!!!**
Needs a little bit more of testing. I'm gonna test it for couple more days. If everything is fine then it should be okay to merge it by the next friday.~

Ready to merge.

### CODE REVIEW

**Comment by K1rakishou** [comment]
Still not ready.

**Comment by K1rakishou** [comment]
Not yet. Lots of changes so have to test them first.

**Comment by K1rakishou** [comment]
~TODO: check whether the pin has DownloadPosts flag in ChanThreadLoader.loadSavedThreadIfItExists() before trying to load local thread from the disk.~

**Comment by K1rakishou** [comment]
@Adamantcheese
Alright, I think it's pretty good. I didn't notice any critical bugs. Just some strange glitch with the downloading animation which sometimes, when clicking the download button, would go to the "downloaded" state right away and stay in that state even though the animation callback is still getting called. I kinda fixed it by using the mutate() method on the animation drawable so it should work. I also changed the AnimatedVectorDrawable to AnimatedVectorDrawableCompat since it's backported to APIs < 23 and there is no need to check for the current API level for some methods.

**Comment by Adamantcheese** [comment]
So this is good to merge then?

**Comment by K1rakishou** [comment]
Yes.

**Pull request merged**
